CC = g++ -g

all: ejemplo_recursion hanoi

ejemplo_recursion: ejemplo_recursion.cpp
	$(CC) ejemplo_recursion.cpp -o ejemplo_recursion

hanoi: hanoi.cpp
	$(CC) hanoi.cpp -o hanoi

clean:
	rm ejemplo_recursion hanoi