CC = g++

all: ejem_apuntadores ejem_referencias

ejem_apuntadores: ejem_apuntadores.cpp
	$(CC) ejem_apuntadores.cpp -o ejem_apuntadores

ejem_referencias: ejem_referencias.cpp
	$(CC) ejem_referencias.cpp -o ejem_referencias

clean:
	rm -f ejem_apuntadores ejem_referencias
