CC = g++ -g

all: ejemplo_sets ejemplo_hash

ejemplo_sets: ejemplo_sets.cpp
	$(CC) ejemplo_sets.cpp -o ejemplo_sets

ejemplo_hash: ejemplo_hash.cpp
	$(CC) ejemplo_hash.cpp -o ejemplo_hash

clean:
	rm ejemplo_sets ejemplo_hash
