CC = g++ -g

all: selectionsort standard_sort

selectionsort: selectionsort.cpp
	$(CC) selectionsort.cpp -o selectionsort

standard_sort: standard_sort.cpp
	$(CC) standard_sort.cpp -o standard_sort

clean:
	rm selectionsort standard_sort
